config/routes.rb
# frozen_string_literal: true
Rails.application.routes.draw do
  root 'blogs#index'
  resources :blogs do
    resources :entries, except: [:index] do
      resources :comments, only: [:new, :create, :approve, :destroy] do
        member do
          patch 'approve'
        end
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  has_many :entries
  validates :title, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :entry
  validates :body, presence: true

  def approved?
    self.status == 'approved'
  end
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :blog
  has_many :comments
  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
# frozen_string_literal: true
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]
  def index
    @blogs = Blog.all
  end

  def show
  end

  def create
    @blog = Blog.new blog_params
    if @blog.save
      redirect_to @blog, notice: 'Successfully blog created.'
    else
      render :new
    end
  end

  def new
    @blog = Blog.new
  end

  def update
    if @blog.update_attributes blog_params
      redirect_to @blog, notice: 'Successfully blog updated.'
    else
      render :edit
    end
  end

  def edit
  end

  def destroy
    if @blog.destroy
      redirect_to @blog, notice: 'Successfully blog destroyed.'
    else
      redirect_to @blog, notice: 'Something went wrong!'
    end
  end

  private

  def set_blog
    @blog = Blog.find(params[:id])
  end

  def blog_params
    params.require(:blog).permit(:title)
  end
end

app/controllers/comments_controller.rb
# coding: utf-8
# frozen_string_literal: true
class CommentsController < ApplicationController
  before_action :set_comment, only: [:approve, :destroy]
  before_action :check_entry, only: [:approve, :destroy]
  def approve
    @comment.status = 'approved'
    if @comment.save
      redirect_to [@comment.entry.blog, @comment.entry], notice: 'Successfully comment approved'
    else
      redirect_to [@comment.entry.blog, @comment.entry], notice: 'Something went wrong!'
    end
  end

  def create
    comment = Comment.new(comment_params.merge(entry_id: params[:entry_id]))
    if comment.save
      # モデルの hook にせずに Web からの投稿の時のみ送信する
      CommentMailer.request_approval(comment).deliver
      redirect_to [comment.entry.blog, comment.entry], notice: 'Successfully comment created'
    else
      redirect_to [comment.entry.blog, comment.entry], notice: 'Something went wrong!'
    end
  end

  def destroy
    if @comment.destroy
      redirect_to [@comment.entry.blog, @comment.entry], notice: 'Successfully comment destroyed.'
    else
      redirect_to [@comment.entry.blog, @comment.entry], notice: 'Something went wrong!'
    end
  end

  private

  def check_entry
    blog = Blog.find(params[:blog_id])
    entry = Entry.find(params[:entry_id])
    comment = Comment.find(params[:id])
    if comment.entry != entry || entry.blog != blog
      redirect_to [comment.entry.blog, comment.entry], notice: 'Comment not found.'
    end
  end

  def set_comment
    @comment = Comment.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/entries_controller.rb
# coding: utf-8
# frozen_string_literal: true
class EntriesController < ApplicationController
  before_action :set_entry, only: [:edit, :show, :update, :destroy]
  before_action :check_blog, only: [:show, :edit, :update, :destroy]

  def show
  end

  def new
    @entry = Entry.new(blog_id: params[:blog_id])
    @entry.blog = Blog.find(params[:blog_id]) # 確実に存在する Blog に限定する
  end

  def create
    entry = Entry.new(entry_params.merge(blog_id: params[:blog_id]))
    if entry.save
      redirect_to [entry.blog, entry], notice: 'Successfully Entry created.'
    else
      redirect_to blog_path(params[:blog_id]), notice: 'Something went wrong!'
    end
  end

  def edit
  end

  def update
    if @entry.update(entry_params)
      redirect_to [@entry.blog, @entry], notice: 'Successfully Entry updated.'
    else
      redirect_to [@entry.blog, @entry], notice: 'Something went wrong!'
    end
  end

  def destroy
    if @entry.destroy
      redirect_to @entry.blog, notice: 'Successfully Entry destroyed.'
    else
      redirect_to @entry.blog, notice: 'Something went wrong!'
    end
  end

  private

  def check_blog
    blog = Blog.find(params[:blog_id])
    entry = Entry.find(params[:id])
    redirect_to blog, notice: 'Entry not found.' unless entry.blog == blog
  end

  def set_entry
    @entry = Entry.find(params[:id])
  end

  def entry_params
    params.require(:entry).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/blogs/_form.html.haml
- if blog.errors.any?
  #error_explanation
    %h2= "#{pluralize(blog.errors.count, "error")}  prohibited this blog from being saved:"
    %ul
      - blog.errors.full_messages.each do |message|
        %li= message

= form_for blog do |f|
  %p
    =f.label :title
    =f.text_field :title
  %p
    =f.submit 'Submit'

app/views/blogs/edit.html.haml
%h1 Edit Blog
= render 'form', blog: @blog

app/views/blogs/index.html.haml
%h1 Blog#index
%table
  %thead
    %tr
      %td Title
      %td
      %td
      %td
  %tbody
    - @blogs.each do |blog|
      %tr
        %td= blog.title.html_safe
        %td= link_to 'Show', blog
        %td= link_to 'Edit', edit_blog_path(blog)
        %td= link_to 'Destroy', blog, method: :delete, data: {confirm: 'Are you sure?'}

=link_to 'New Blog', new_blog_path

app/views/blogs/new.html.haml
%h1 New Blog

= render 'form', blog: @blog

app/views/blogs/show.html.haml
%div
  %h1= @blog.title

  = link_to 'Edit', edit_blog_path(@blog)
  = link_to 'Back', blogs_path

%div
  %h2 Listing Entries
  -if @blog.entries.present?
    %table
      %thead
        %tr
          %td Title
          %td Body
          %td
          %td
          %td
      %tbody
        - @blog.entries.order(created_at: :desc).each do |entry|
          %tr
            %td= entry.title
            %td= entry.body.truncate(20, separator: /(。|\.| )/)
            %td= link_to 'Show', [@blog, entry]
            %td= link_to 'Edit', edit_blog_entry_path(@blog, entry)
            %td= link_to 'Destroy', [@blog, entry], method: :delete, data: { confirm: 'Are you sure?' }
  -else
    %p まだ記事は有りません
  =link_to 'New Entry', new_blog_entry_path(@blog)

app/views/entries/_form.html.haml
-# # =form_for(entry, url: blog_entries_path(entry.blog, entry)) do |f|
=form_for([entry.blog,entry]) do |f|
  %p
    = f.label :title
    = f.text_field :title
  %p
    = f.label :body
    = f.text_area :body
  %p
    = f.submit 'Submit'

app/views/entries/edit.html.haml
%h1 Edit Entry
= render 'form', entry: @entry

app/views/entries/new.html.haml
%h1 New Entry
=render 'form', entry: @entry

app/views/entries/show.html.haml
%article
  %h1= @entry.title
  %div= @entry.body
  =link_to 'Edit', edit_blog_entry_path(@entry.blog, @entry)
  =link_to 'Back', @entry.blog

%div
  %h2 Listing Comments
  %table
    %thead
      %tr
        %td Body
        %td
        %td
    %tbody
      - @entry.comments.each do |comment|
        %tr
          %td= comment.approved? ? comment.body : '(承認待ち)'
          %td= link_to( 'Approve', approve_blog_entry_comment_path(@entry.blog, @entry, comment), method: :patch ) unless comment.approved?
          %td= link_to( 'Destroy', [ @entry.blog, @entry, comment ], method: :delete, data: { confirm: 'Are you sure?'} )
  %h3 New Comment
  = form_for([ @entry.blog, @entry, Comment.new ]) do |f|
    %p
      = f.label :body
      = f.text_area :body
    %p
      = f.submit 'Submit'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Blog3
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .notice= notice
    = yield